name: SendChanges-to-DockerHub

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerec2:v1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerec2:v1

      - name: Deploy to EC2 via Docker (Pull and Run Docker container)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST4_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            sudo docker rm -f dockerec2 || true
            sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/dockerec2:v1 || true

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/dockerec2:v1

            sudo docker run -d -p 80:80 --name dockerec2 ${{ secrets.DOCKER_USERNAME }}/dockerec2:v1
