name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ksrobalino
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ksrobalino/my-app:main

      - name: Deploy and run Docker container on Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Instalar Docker si no está disponible
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

            # Descargar la imagen desde Docker Hub
            sudo docker pull ksrobalino/my-app:main

            # Detener y eliminar contenedores antiguos
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            # Iniciar el nuevo contenedor
            sudo docker run -d --name my-app -p 80:80 ksrobalino/my-app:main

  deploy_server2:
    name: Deploy to Server 2 on main branch push with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ksrobalino
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ksrobalino/my-app:main

      - name: Deploy and run Docker container on Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Instalar Docker si no está disponible
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

            # Descargar la imagen desde Docker Hub
            sudo docker pull ksrobalino/my-app:main

            # Detener y eliminar contenedores antiguos
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            # Iniciar el nuevo contenedor
            sudo docker run -d --name my-app -p 80:80 ksrobalino/my-app:main
