 deploy_qa:
    name: Deploy to QA with Docker
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout the files
        uses: actions/checkout@v2

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Usar el nombre de usuario configurado en los secretos
          password: ${{ secrets.DOCKER_PASSWORD }}  # Usar el token o contraseña configurados en los secretos

      # Paso 3: Construir y subir la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Directorio donde se encuentra el código fuente y Dockerfile
          file: ./Dockerfile  # Ubicación del Dockerfile
          push: true  # Subir la imagen a Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:qa  # Etiqueta para la imagen en Docker Hub

      # Paso 4: Desplegar en el servidor de QA usando Docker
      - name: Deploy and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_QA }}  # Dirección DNS del servidor de QA
          username: ${{ secrets.USERNAME }}  # Nombre de usuario del servidor de QA
          key: ${{ secrets.EC2_SSH_KEY }}  # Clave SSH para el servidor
          script: |
            # Verificar si Docker está instalado
            if ! command -v docker &> /dev/null
            then
              echo "Instalando Docker desde los repositorios oficiales..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            fi

            # Descargar la imagen desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:qa

            # Detener y eliminar contenedores antiguos
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            # Iniciar el nuevo contenedor
            sudo docker run -d --name my-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-app:qa