name: SendChanges-to-DockerHub

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Deploy to EC2 via Docker (Pull and Run Docker container)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST4_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Actualiza el sistema y Docker
            sudo apt-get -y update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # Elimina cualquier contenedor anterior (si existe)
            sudo docker rm -f myapp || true

            # Elimina cualquier imagen anterior (si existe)
            sudo docker rmi -f ${{ secrets.DOCKER_USERNAME }}/myapp:latest || true

            # Obtiene la última imagen desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest

            # Ejecuta el contenedor
            sudo docker run -d -p 80:80 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
