name: Deploy to QA with Docker

on:
  push:
    branches:
      - qa

jobs:
  deploy_qa:
    name: Deploy to QA with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ksrobalino
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ksrobalino/my-app:qa

      - name: Deploy and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_QA }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Verificar si Docker está instalado
            if ! command -v docker &> /dev/null
            then
              echo "Instalando Docker desde los repositorios oficiales..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            fi

            # Descargar la imagen desde Docker Hub
            sudo docker pull ksrobalino/my-app:qa

            # Detener y eliminar contenedores antiguos
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            # Iniciar el nuevo contenedor
            sudo docker run -d --name my-app -p 80:80 ksrobalino/my-app:qa