name: SendChanges-to-EC2 (Docker QA)

on:
  push:
    branches:
      - qa

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

      # Deploy to EC2 Instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST4_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Docker is running
            sudo systemctl start docker || true

            # Stop and remove any existing container
            if sudo docker ps -q -f name=webapp; then
              sudo docker stop webapp
              sudo docker rm webapp
            fi

            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

            # Run the new Docker container
            sudo docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
